### ISSUE TITLE
Classification Scores after Ensemble

### ISSUE THREAD

**Issue by Eleanor11111** [liujf69/EPP-Net-Action#2]
Hello, may I ask how to obtain each Classification score after Pose+Parsing Ensemble?

**Comment by liujf69** [comment]
In fact, when ensemble the two modalities, the shape of the final_score in [Ensemble.py](https://github.com/liujf69/EPP-Net-Action/blob/master/Ensemble/Ensemble.py) is also **[num_samples, num_classes]**, and it is necessary to **normalize** the scores of the 120 classes **in each sample**. I hope my answer can help you.

**Comment by Eleanor11111** [comment]
ok got it. Thanks for the swift reply! Best wish!
